CREATE TABLE IF NOT EXISTS presentation
(
    id          INTEGER     NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id_user     INTEGER     NOT NULL,
    name        VARCHAR(30) NOT NULL,
    status_code TINYINT     NOT NULL DEFAULT 0,
    created_at  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE (id, id_user)
);

CREATE TABLE IF NOT EXISTS page
(
    id              INTEGER  NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id_presentation INTEGER  NOT NULL,
    timing          INTEGER  NOT NULL,
    metadata        JSON     NOT NULL,
    status_code     TINYINT  NOT NULL DEFAULT 0,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);